USE [master]
GO

/****** Object:  Database [Automation]    Script Date: 6/28/2019 10:00:40 AM ******/
CREATE DATABASE [Automation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QA_Automation', FILENAME = N'D:\Data_Userdb\QA_Automation.mdf' , SIZE = 2228224KB , MAXSIZE = UNLIMITED, FILEGROWTH = 131072KB )
 LOG ON 
( NAME = N'QA_Automation_log', FILENAME = N'L:\Data_Userdb\QA_Automation_log.ldf' , SIZE = 196608KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Automation] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Automation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Automation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Automation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Automation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Automation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Automation] SET ARITHABORT OFF 
GO

ALTER DATABASE [Automation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Automation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Automation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Automation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Automation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Automation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Automation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Automation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Automation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Automation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Automation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Automation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Automation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Automation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Automation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Automation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Automation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Automation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Automation] SET  MULTI_USER 
GO

ALTER DATABASE [Automation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Automation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Automation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Automation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Automation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Automation] SET QUERY_STORE = OFF
GO

USE [Automation]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Automation] SET  READ_WRITE 
GO

