source 'https://rubygems.org'
gem 'json'
gem 'net-sftp'
gem 'net-ssh'
gem 'pry'
gem 'selenium-webdriver'
#gem 'tiny_tds', '1.3'
gem 'nokogiri'
#gem 'google_drive'
#gem 'certified'
#gem 'sheet2hash'
gem 'roo-xls'
gem 'roo'
#gem 'rest-client'
#gem 'bigdecimal'
gem 'httparty'
gem 'net-http'
#gem 'socket'
gem 'open-uri'
gem  'test-unit'
gem 'mysql2'
gem 'net-ssh-gateway', '~> 2.0'
gem 'logging'
gem 'openssl'
gem 'webdriver'
gem 'pg'
gem 'ffi'
gem 'pdf-reader'
