source 'https://rubygems.org'
#gem 'json'
gem 'net-sftp'
gem 'net-ssh'
gem 'pry'
gem 'selenium-webdriver'
gem 'tiny_tds', '1.3'
gem 'nokogiri'
gem 'google_drive'
gem 'certified'
gem 'sheet2hash'
gem 'roo-xls'
gem 'roo'
gem 'rest-client'
#gem 'bigdecimal'